# Generated by Django 2.2 on 2019-05-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
