# Generated by Django 2.2 on 2019-05-13 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workapp', '0004_auto_20190510_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='photo',
            field=models.ImageField(blank=True, help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='image/userphoto'),
        ),
        migrations.CreateModel(
            name='Appliedjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
                ('job_id', models.OneToOneField(on_delete=True, to='workapp.JobPost')),
            ],
            options={
                'verbose_name': 'Applied Jobs',
                'db_table': 'Applied_Jobs',
            },
        ),
    ]
