# Generated by Django 2.2 on 2019-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0005_auto_20190513_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
