# Generated by Django 2.2 on 2019-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0006_auto_20190513_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='photo',
            field=models.FileField(help_text='Upload only .png, .jpg & .jpeg image extension.', null=True, upload_to='image/userphoto'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='resume',
            field=models.FileField(help_text='Upload only .txt, .pdf & .word file extension.', null=True, upload_to='image/userresume'),
        ),
    ]
