# Generated by Django 2.2 on 2019-05-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0007_auto_20190513_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/userphoto/'),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='resume',
            field=models.FileField(null=True, upload_to='image/userresume/'),
        ),
    ]
