# Generated by Django 2.2 on 2019-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workapp', '0008_auto_20190513_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.OneToOneField(on_delete=True, to='workapp.CompanyRegister')),
                ('user_id', models.OneToOneField(on_delete=True, to='workapp.UserRegister')),
            ],
            options={
                'verbose_name': 'Selected Candidate',
                'db_table': 'Selected_Candidate',
            },
        ),
    ]
